var en_us = {
    Home: "Home",
    Downloads: "Downloads",
    Screenshot: "Screenshots",
    Changelog: "Changelog",
    Chat: "Chat on Gitter",
    Description: "Screen, webcam and sketchboard recorder with an integrated editor.",
    Title: "ScreenToGif - Record your screen, edit and save as a Gif or video",
    Download: "Download",
    DownloadPort: "Download (Portable)",
    Help: "User Guide",
    Source: "Source",
    Donate: "Donate",
    Donate2: "Donate", // Big button.
    More: "More screenshots",
    Features: "Features",
    Portable: "A portable, single executable and very small-sized application, only ~611KB! (compressed).",
    Free: "Free and open source application, without any ads!",
    Recorders: "3 ways of recording your content: Screen, Webcam and Sketchboard.",
    Powerful: "A powerful editor with lots of options! You can edit your recording or even edit gifs from other sources.",
    Export: "You can export as Gif, Video or save as a project to edit later.",
    Clean: "A clean and consistent interface, powered by WPF.",
    Languages: "Over 18 different languages. Automatically detects the language of your system, defaults to English.",
    Options: "Lots of options. You can even change the colors of the recorder. :)",
    Active: "Active development, integrated with users needs. Feedback is very welcome!",
    Requirements: "Requirements",
    Windows: "Windows Vista or later",
    Framework: ".Net Framework 4.6.1 or later",
    Copyright: "Copyright",
    Releases: "Latest releases",
    Release: "Release name",
    Installer: "Installer",
    Portable2: "Portable",
    Count: "Download count",
    Date: "Release date",
    Days: "Active days",
    Support: "Support us",
    Links: "Links",
    Info1: "It's a free and open-source app. No ads, nothing shady or obscure. If you have any doubt, feel free to ask or browse the source code.",
    Info2: "Donations are the only source of income of ScreenToGif. If you would like to support this project then please consider donating.",
    Info3: "There's 3 ways to donate, via Patreon, Paypal, or Steam (it's possible to donate games or credits).",
    Donators: "Patrons/Donators",
    Donator: "Name",
    Website: "Website",
    Amount: "Total donation amount",
    From: "From",
    Version: "Version: ",
    Released: "Released: ", //As in "released in" october.
    DaysAgo: " days ago",
    HoursAgo: " hours ago",
    DownloadCount: "Download count: ",
};